micronaut:
  application:
    name: pixKeymanagerRest


grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    chave-pix:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 5
